public enum Command {
    SHOW_MENU,
    SHOW_HELP,
    START_NEW_GAME,
    RETURN_TO_GAME,
    QUIT_GAME,
    SET_STATE,
    HOVERING,
    NOT_HOVERING,
    PREV_HELP_PAGE,
    NEXT_HELP_PAGE,
    GAME_MODE_EASY,
    GAME_MODE_MEDIUM,
    GAME_MODE_HARD,
    BOARD_SIZE_3X3,
    BOARD_SIZE_3X5,
    BOARD_SIZE_5X5,

}
